Fix ''undefined method 'each' for '''':String app/controllers/extension_controller.rb:34:in 'private_domain'''; Fix errors related to incomplete removal of 'budgeted_hours'; fix possible error when not setting SFDC user when deciding whether to attempt auto-linking an SFDC account.